### ISSUE TITLE
missing gitignore in generator

### ISSUE THREAD

**Issue by SkeLLLa** [DarkDaskin/generator-userscript#1]
Hello. First of all thanks for generator.

The bug is quiet simple. Npm by default when you do npm publish ignores `.gitignore`. As a result file `generator-userscript/generators/app/templates/.gitignore` is not present in npm package and it cause generator to fail.

**Comment by DarkDaskin** [comment]
Thanks for reporting. I should have tried to actually install and run what I have published to npm.
